### ISSUE TITLE
mongodb + django

### ISSUE THREAD

**Issue by rpalloni** [mikeckennedy/build-pypi-mongodb-webcast-series#1]
Hi! Thanks for your work.
I'd like to ask if there are any examples/tutorial/docs about using mongodb in Django framework.
Could you help?

Thanks

**Comment by mikeckennedy** [comment]
Hi. I don't combine these two things much because I don't use Django really. Here's an option: 

https://django-mongodb-engine.readthedocs.io/en/latest/
